select * from sales
limit 10;
--1. What is the tOotal revenue generated by male vs female customers

SELECT gender, SUM(purchase_amount) AS total_revenue
FROM sales
GROUP BY gender;

--2. Which customers used a discount but still spent more than the average purchase amount

SELECT customer_id, purchase_amount
FROM sales
WHERE discount_applied = 'Yes' and purchase_amount > (SELECT AVG(purchase_amount) FROM sales);

--3. Which are the top 5 products with the highest average review rating

SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),2) as average_review_rating
FROM sales
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;

--4. Compare the average Purchase Anmounts between the Express and Standard Shipping

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM sales
WHERE shipping_type in('Express','Standard')
GROUP BY 1;

--5. Do subscribed customers spend more? Compare the average spend and total revenue between subscribers and non-subscribers

SELECT subscription_status, 
	ROUND(AVG(purchase_amount),2) AS average_spend,
	SUM(purchase_amount) AS total_revenue
FROM sales
GROUP BY 1

--6. Which 5 products have the highest percentage of purchases with discount applied

SELECT 
	item_purchased,
    100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /COUNT(*) AS percent_of_purchases
FROM sales
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;

--7.Segment the customers into New, Returning,Loyal based on their total number of previous purchases and show the count of each segment
WITH customer_type as (
 	SELECT customer_id, previous_purchases,
	 CASE
	 	WHEN previous_purchases = 1 THEN 'New'
		 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		 ELSE 'Loyal'
	 END AS customer_segment
	FROM sales
)
SELECT customer_segment, COUNT(*) AS segment_count
FROM customer_type
GROUP BY customer_segment;

--8. What are the top 3 most purchased products withing each category

WITH item_counts AS (
 SELECT category,
 		item_purchased,
		 COUNT(customer_id) AS total_orders,
		 ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
 FROM sales
 GROUP BY category, item_purchased	 
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM sales
WHERE previous_purchases > 5
GROUP BY subscription_status


--10. What is the revenue contribution of each age_group

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM sales
GROUP BY age_group
ORDER BY 2 DESC;










